<?php

// autoload_psr4.php @generated by Composer

$vedorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vedorDir);

return array(
    'PHPMailer\\PHPMailer\\' => array($vedorDir . '/phpmailer/phpmailer/src'),
);
